services:

  python:
    image: mcr.microsoft.com/devcontainers/python:3.11
    command: /bin/bash -c "while sleep 1000; do :; done"
    environment:
      - PYTHONUNBUFFERED=1
    # ports:
    #  - "8000:8000"
    volumes:
      - .:/workspace:cached
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    # ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: